services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ./data:/app/data
      - ./backend/static/uploads:/app/static/uploads
      - invoices_data:/app/static/invoices
    ports:
      - "8088:8080"

  frontend-client:
    build:
      context: ./frontend/client
      dockerfile: ../../docker/frontend.client.Dockerfile
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE: /api
      NMM_BACKEND_URL: http://backend:8080
    ports:
      - "3002:3002"

  frontend-admin:
    build:
      context: ./frontend/admin
      dockerfile: ../../docker/frontend.admin.Dockerfile
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE: /api
      NMM_BACKEND_URL: http://backend:8080
    ports:
      - "3012:3001"

volumes:
  invoices_data:
